#!/bin/bash

xargs -L 1 -I {} -P 2 bash -c '{}' <<"EOF"
srun ls cats && echo "FAILED" || echo "1 - OK"; sleep 3
srun ls $HOME && echo "0 - OK" || echo "FAILED"; sleep 3
srun hostname && echo "0 - OK" || echo "FAILED"; sleep 3
EOF
